// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('pernas.example', []);

  angular.module('pernas.example').directive('example', [
    '$timeout', function($timeout) {}, {
      restrict: 'E',
      template: 'HOLA {{name}}',
      controller: [
        '$scope', function($scope) {
          return $scope.name = 'Jaume';
        }
      ]
    }
  ]);

}).call(this);
