// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('pernas.example', []).directive('example', [
    '$timeout', function($timeout) {
      return {
        restrict: 'E',
        template: 'HOLA TIO'
      };
    }
  ]);

}).call(this);
